# Generated by the ansible mailcow role — do not edit by hand.
#
# These two values cannot be written down ahead of time: the DKIM key does not
# exist until mailcow has been installed and the domain created inside it, and
# the MTA-STS policy is only announced once mailcow is actually serving it.
#
# They live in a file rather than being passed as -var on the command line so
# that the Terraform configuration is complete on its own. With -var, a bare
# `terraform plan` run by hand saw mail_dkim_txt default to "" and planned to
# DESTROY the live DKIM record — a loaded gun for anyone who ran plan without
# knowing the incantation. Nothing here is secret: a DKIM public key is
# published in DNS by definition.

mail_dkim_txt        = "v=DKIM1;k=rsa;t=s;s=email;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7U9Ki6Ql5Z/A/rkyMPN6IbKnnGQdZ9Cdsvvm/pBYA2fmCjtGglzpPK09pH71Az3qW8LoJQV2rnKu1DbbN7ZXaeG/WHDRAjQcCCbEiExGGOyPshRzP93sdSCpoVKpNyu8VaHU+KOcMm3qS76gg5r8l5BsFSjbxDwDmS+AtJgFuF+KQAgm+hEEc5tF+KdaLSm9II64cwotMt8KiFyk7uvo+6ACOnH0M8Ar1scuFyZYEzl9hIzG01fLmPRtjYkhp7FgLiiuWuZCTst/SrLp+0A28sJH5gTcfqGPcGmWpnWoDnNlpg1H+GJn5e8E7KC+BOtImSU7zhtxNKhGqZLWKUsYOQIDAQAB"
mail_dkim_selector   = "dkim"
mail_mta_sts_enabled = false
