# Generated by the ansible mailcow role — do not edit by hand.
#
# These values cannot be written down ahead of time: a DKIM key does not exist
# until mailcow has been installed and the domain created inside it, and an
# MTA-STS policy is only announced once mailcow is actually serving it. Both
# are per-domain, so both are maps; a domain absent from either map keeps the
# corresponding record out of the plan entirely.
#
# They live in a file rather than being passed as -var on the command line so
# that the Terraform configuration is complete on its own. With -var, a bare
# `terraform plan` run by hand saw mail_dkim default to {} and planned to
# DESTROY the live DKIM record — a loaded gun for anyone who ran plan without
# knowing the incantation. Nothing here is secret: a DKIM public key is
# published in DNS by definition.

mail_dkim_selector = "dkim"

mail_dkim = {
  "joachimjasmin.com" = "v=DKIM1;k=rsa;t=s;s=email;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7U9Ki6Ql5Z/A/rkyMPN6IbKnnGQdZ9Cdsvvm/pBYA2fmCjtGglzpPK09pH71Az3qW8LoJQV2rnKu1DbbN7ZXaeG/WHDRAjQcCCbEiExGGOyPshRzP93sdSCpoVKpNyu8VaHU+KOcMm3qS76gg5r8l5BsFSjbxDwDmS+AtJgFuF+KQAgm+hEEc5tF+KdaLSm9II64cwotMt8KiFyk7uvo+6ACOnH0M8Ar1scuFyZYEzl9hIzG01fLmPRtjYkhp7FgLiiuWuZCTst/SrLp+0A28sJH5gTcfqGPcGmWpnWoDnNlpg1H+GJn5e8E7KC+BOtImSU7zhtxNKhGqZLWKUsYOQIDAQAB"
  "ipseis.eu"         = "v=DKIM1;k=rsa;t=s;s=email;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAunh6HNAd4a8i2wz/DOtrvs1oasjRTfLNqOZKsZb1rXFaJNwll7reAYitY7CVoNiGwIwU/XxXuogJQ0Sa4aI73NX6kayfbi+ysu+DwYGi8eaFqPSOkJHwNvMlSe91KuLcomrixtD7zr7zX7y92Wx4rQ4ANyiW67mXgO2EhL496sRdz/9SMXZUVnIhkVMSLfpQVVgrsUdOp3luwOLp39n7vWMfmgYNOJtdzVnJ2owb06nCk/VZmXBhdxqeBBlbGu2acmXbDC9t2mXoB8Y0RFFKdqGT+lenokTCON1f/1Dny4TFN4FTbGMwz9W4gfCPIElhh2RUx/mWdITrsaRfkceIHQIDAQAB"
  "odyssai.app"       = "v=DKIM1;k=rsa;t=s;s=email;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA69wv6AkiHfd3O+1avyYKjXD+VuckWDmtLWDgACQWS3Wx5Jx7xha1tOPOyWsZBGPmjMJXPoAcDdtXzRkn6pqwRHqYmzFXOJr8C5AXGs5H11jEsLFMBnwfdIBaV11mP+rrL9j+BXgFpvDCnhynXpZWY09zTlxZWwEYi2H0i0gcremTl3cQfxfQdVg1eKP1V/LLZh+uKEPKKGSzl1m1ix/4PReXWjpNtdGhpaLYBTGSSUB3jh9HSjEoSWFnNdNnAHAnm+VF/5MX/LbBLYG+BS8acx59riMvbYDzhpAaMMHRKGEqd/6rsppqiXwvIt0neM76ZfttOYVfCVbU6Y2g6zCqXwIDAQAB"
}

mail_mta_sts_serving = {
  "joachimjasmin.com" = false
  "ipseis.eu"         = false
  "odyssai.app"       = false
}
