---
- name: Create stack directory
  ansible.builtin.file:
    path: "{{ komodo_app_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Create Periphery directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0750"
  loop:
    - "{{ komodo_periphery_root_dir }}"
    - "{{ komodo_backups_path }}"

- name: Deploy env files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ komodo_app_dir }}/{{ item }}"
    owner: root
    group: root
    mode: "0600"
  loop:
    - komodo.env
  no_log: true

- name: Deploy compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ komodo_app_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0640"

- name: Deploy services
  community.docker.docker_compose_v2:
    project_src: "{{ komodo_app_dir }}"
    state: present
    recreate: auto
    remove_orphans: true
    wait: true
    wait_timeout: 300
