---
all:
  children:
    portfolio:
      hosts:
        main:
          # Vars
          ansible_host: "{{ vault_ansible_host }}"
          ansible_port: "{{ vault_ansible_port }}"
  vars:
    ansible_become: true
    ansible_become_method: sudo
    ansible_deprecation_warnings: false
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: /usr/bin/python3
    vrack_cidr: 24
    vrack_mtu: 1500
